name: CI

on:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.os }} / PHP ${{ matrix.php }} / ${{ matrix.phpts }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Windows x86_64 - PHP 8.5 ZTS
          - os: windows
            runner: windows-latest
            php: "8.5"
            phpts: ts
            rust: nightly
            clang: ""

          # Windows x86_64 - PHP 8.5 NTS
          - os: windows
            runner: windows-latest
            php: "8.5"
            phpts: nts
            rust: nightly
            clang: ""
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
        env:
          phpts: ${{ matrix.phpts }}
          debug: true
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy
      - run: rustup show
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ env.RUST_CACHE_PREFIX }}
      - name: Build
        run: cargo build --release

  build-php-test:
    name: ${{ matrix.platform.os }} / PHP ${{ matrix.php }} / ${{ matrix.ts }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-latest
            rust: stable
            lib: php_test.so
            flags: "-C link-arg=-Wl,-undefined,dynamic_lookup"
          - os: macos-latest
            rust: stable
            lib: php_test.dylib
            flags: "-C link-arg=-Wl,-undefined,dynamic_lookup"
          - os: windows-latest
            # ext-php-rs requires nightly Rust when on Windows.
            rust: nightly
            lib: php_test.dll
            flags: ""
        php:
          - '8.3'
          - '8.4'
          - '8.5'
        ts:
          - nts
          - zts
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v5
      - run: rustup show
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
        env:
          debug: true
          phpts: ${{ matrix.ts }}
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy
      - run: php -v
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ env.RUST_CACHE_PREFIX }}
      - if: ${{ matrix.platform.flags == '' }}
        name: Build PHP extension (no RUSTFLAGS)
        run: cargo build --release
      - if: ${{ matrix.platform.flags != '' }}
        name: Build PHP extension (with RUSTFLAGS)
        run: cargo build --release
        env:
          RUSTFLAGS: ${{ matrix.platform.flags }}
