name: CI

on:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  build-php-test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-latest
            rust: stable
            lib: php_test.so
            flags: "-C link-arg=-Wl,-undefined,dynamic_lookup"
          - os: macos-latest
            rust: stable
            lib: php_test.dylib
            flags: "-C link-arg=-Wl,-undefined,dynamic_lookup"
          - os: windows-latest
            # ext-php-rs requires nightly Rust when on Windows.
            rust: nightly
            lib: php_test.dll
            flags: ""
        php:
          - '8.3'
          - '8.4'
          - '8.5'
        ts:
          - nts
          - zts
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.platform.rust }}
      - run: rustup show
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
        env:
          debug: true
          phpts: ${{ matrix.ts }}
      - run: php -v
      - if: ${{ matrix.platform.flags == '' }}
        name: Build PHP extension (no RUSTFLAGS)
        run: cargo build --release
      - if: ${{ matrix.platform.flags != '' }}
        name: Build PHP extension (with RUSTFLAGS)
        run: cargo build --release
        env:
          RUSTFLAGS: ${{ matrix.platform.flags }}
